### ISSUE TITLE
The source code has no license

### ISSUE THREAD

**Issue by gpoo** [kwonalbert/riffle#1]
The lack of license means *All rights reserved* and it may affect the adoption (for example, porting the ode to other languages or distributing the code).

**Comment by BenjaminHCCarr** [comment]
Seeing as the math and protocol are public and published in Proceedings on Privacy Enhancing Technologies an De Gruyter Open Access Journal

And all of that is licensed:
Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 License. (CC BY-NC-ND 4.0)

http://www.degruyter.com/downloadpdf/j/popets.2015.2016.issue-2/popets-2016-0008/popets-2016-0008.xml

I would think some some FOSS license is appropriate, see:
http://choosealicense.com/licenses/
https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses
https://opensource.org/licenses

Mozilla Public License 2.0 is likely closest to the way you did the paper:
http://choosealicense.com/licenses/mpl-2.0/


Permissions	
* Commercial Use
* Distribution
* Modification
* Patent Use
* Private Use

Conditions
* Disclose Source
* License and Copyright Notice
* Same License

Limitations
* Hold Liable
* Trademark Use

**Comment by kwonalbert** [comment]
Thanks for the suggestions. I'll take a deeper look and add a license soon.
